### ISSUE TITLE
stress test error: SEGV from XXH3

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#284]
azure instances - Standard_L16s_v3
cmd - make clean && TEST_TMPDIR=/data COMPILE_WITH_ASAN=1 make -j16 blackbox_crash_test
same error when TEST_TMPDIR=/dev/shm and when /data is mounted only on 1 disk. 
on base/v7.7.3. CI passed on this branch.

error is:
```==23139==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x556546e82a8b bp 0x7fa32c133350 sp 0x7fa32c133200 T36)
==23139==The signal is caused by a READ memory access.
==23139==Hint: address points to the zero page.
    #0 0x556546e82a8a in _mm512_add_epi64 /usr/lib/gcc/x86_64-linux-gnu/9/include/avx512fintrin.h:739
    #1 0x556546e82a8a in XXH3_accumulate_512_avx512 util/xxhash.h:3613 
    #2 0x556546e82a8a in XXH3_accumulate util/xxhash.h:4230
    #3 0x556546e82a8a in XXH3_hashLong_internal_loop util/xxhash.h:4252
    #4 0x556546e82a8a in XXH3_hashLong_64b_internal util/xxhash.h:4315 
    #5 0x556546e82a8a in XXH3_hashLong_64b_default util/xxhash.h:4348
    #6 0x556546e85cdc in XXH3_64bits_internal util/xxhash.h:4415
    #7 0x556546e85cdc in ROCKSDB_XXH3_64bits util/xxhash.h:4424
    #8 0x55654647856a in rocksdb::log::Reader::ReadRecord(rocksdb::Slice*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, rocksdb::WALRecoveryMode, unsigned long*) db/log_reader.cc:110
    #9 0x556546224437 in rocksdb::DBImpl::RecoverLogFiles(std::vector<unsigned long, std::allocator<unsigned long> > const&, unsigned long*, bool, bool*, rocksdb::DBImpl::RecoveryContext*) db/db_impl/db_impl_open.cc:1092
    #10 0x5565462331c4 in rocksdb::DBImpl::Recover(std::vector<rocksdb::ColumnFamilyDescriptor, std::allocator<rocksdb::ColumnFamilyDescriptor> > const&, bool, bool, bool, unsigned long*, rocksdb::DBImpl::RecoveryContext*) db/db_impl/db_impl_open.cc:651
    #11 0x556546257d50 in rocksdb::DBImplReadOnly::OpenForReadOnlyWithoutCheck(rocksdb::DBOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<rocksdb::ColumnFamilyDescriptor, std::allocator<rocksdb::ColumnFamilyDescriptor> > const&, std::vector<rocksdb::ColumnFamilyHandle*, std::allocator<rocksdb::ColumnFamilyHandle*> >*, rocksdb::DB**, bool) db/db_impl/db_impl_readonly.cc:287
    #12 0x55654625cf81 in rocksdb::DB::OpenForReadOnly(rocksdb::DBOptions const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<rocksdb::ColumnFamilyDescriptor, std::allocator<rocksdb::ColumnFamilyDescriptor> > const&, std::vector<rocksdb::ColumnFamilyHandle*, std::allocator<rocksdb::ColumnFamilyHandle*> >*, rocksdb::DB**, bool) db/db_impl/db_impl_readonly.cc:272
    #13 0x556545e8356d in rocksdb::StressTest::TestBackupRestore(rocksdb::ThreadState*, std::vector<int, std::allocator<int> > const&, std::vector<long, std::allocator<long> > const&) db_stress_tool/db_stress_test_base.cc:1578
    #14 0x556545eb9f2c in rocksdb::StressTest::OperateDb(rocksdb::ThreadState*) db_stress_tool/db_stress_test_base.cc:837
```
checking on AWS c5d.9xlarge instance - same error. 

checking on main (based on rocksdb 7.2.2) - **doesnt happen**

maybe its the - TEST_TMPDIR=/data
CI doesnt have this option.

**Comment by Yuval-Ariel** [comment]
CI instances are running a docker container with ubuntu18:04 and install build-essential which installs g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 . 
switching a from g++ 9.4 to 7.5 on an azure instance also solves this problem. 

the question is:
why doesnt this happen with g++ 9.4 on 7.2.2 ?

**Comment by mrambacher** [comment]
Does this happen on RocksDB 7.7.3?  Does it happen with both compilers (g++ 7.5 and g++ 9.4) there?  If it happens with on "plain RocksDB", can we try a few other versions of Rocks to narrow down when it might have been introduced?  (Additionally, we might want to see if it is still happening in RocksDB latest).

If it happens in plain RocksDB, we might want to open an issue in that repo as well to see if others in the community have experienced this or if anyone has a solution.

**Comment by Yuval-Ariel** [comment]
the error happens with g++ 7.5 as well just with a much lower frequency..

**Comment by Yuval-Ariel** [comment]
@speedbmike  any updates?

**Comment by Yuval-Ariel** [comment]
this reproduces with g++ 11 and on latest rocksdb main as well.
