### ISSUE TITLE
Stress error: 'utf-8' codec can't decode byte 0xe3

### ISSUE THREAD

**Issue by Yuval-Ariel** [speedb-io/speedb#496]
running blackbox_crash_test resulted in the error:
```
Traceback (most recent call last):
  File "tools/db_crashtest.py", line 1280, in <module>
    main()
  File "tools/db_crashtest.py", line 1267, in main
    blackbox_crash_main(args, unknown_args)
  File "tools/db_crashtest.py", line 980, in blackbox_crash_main
    hit_timeout, retcode, outs, errs = execute_cmd(cmd, cmd_params["interval"])
  File "tools/db_crashtest.py", line 886, in execute_cmd
    return hit_timeout, child.returncode, outs.decode("utf-8"), errs.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe3 in position 529: invalid continuation byte

```

**Comment by Yuval-Ariel** [comment]
the junk msg is the cause of misplacing the args in the call to VerifyOrSyncValue where the value from the db was inserted into the msg_prefix parameter instead of "Pre-Put Get verification" in no_batched_ops_stress.cc , Status TestPut
```
    if (FLAGS_verify_before_write) {
      std::string from_db;
      Status s = db_->Get(read_opts, cfh, k, &from_db);
      if (!VerifyOrSyncValue(rand_column_family, rand_key, read_opts, shared,
                             /* msg_prefix */ "Pre-Put Get verification",
                             from_db, s, /* strict */ true)) {
        return s;
      }
    }
```
